name: Terraform Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: terraform init -backend=false
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - run: echo ${{ steps.validate.outputs.stdout }}

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all 
          git commit -m 'teraform formatting'
          git push

  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - uses: actions/checkout@v2
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          locale: "US"

  docs:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: terraform-docs/gh-actions@v0.11.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

  tflint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - uses: actions/checkout@v2
      - uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
